
a = 10
b = 0

try:
    raise Exception("This is from the Try Block")
except Exception as e:
    print("e Value: ", e)
